name: Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Download libimageflow DLL
        shell: bash
        run: |
          curl -sL https://github.com/imazen/imageflow/releases/download/v2.3.0-rc01/imageflow-v2.3.0-rc01-win-x86_64.zip -o imageflow.zip
          unzip imageflow.zip

      - name: Download test image
        shell: bash
        run: curl -sL https://jpeg.org/images/jpeg2000-home.jpg > image.jpg

      - name: Test
        run: go test -ldflags="-r ." -v
